### ISSUE TITLE
Update addon to reflect 7.3 Artifact Knowledge (and research) changes

### ISSUE THREAD

**Issue by rdw-software** [SacredDuckwhale/TotalAP#36]
This is to keep track of 7.3 changes and make sure everything still works as intended.

Mandatory fixes:
- [x] Remove Artifact Research Notes from DB (as they're now unusable)
- [x] Remove research progress text from tooltips (researching has effectively been removed)
- [x] Artifact Knowledge still tracks the old currency, which seems to be stuck at AK 40. Use C_ArtifactUI.GetArtifactKnowledgeLevel() instead, which is only available during artifact updates and therefore needs to be cached and updated along with the other cache data (volatile, not persistent)

These need to be added to make the addon function as expected going forward from patch 7.3.
 
Optional clean-up tasks:
- [ ] Remove the entire ResearchTomesDB parts and code in ArtifactInterface (the DB is now empty for all intents and purposes)
- [ ] Remove the preferential treatment for tomes as well as the related  artifactCache entries (foundTome, etc.)
- [ ] Remove the entire "maxed artifact" code, as all artifacts are automatically set to tier 2 when they reach 35 traits, so this is now pointlessM

Might as well keep this unless it affects performance negatively. It'll get cleaned up with the next refactoring pass, anyway.

Related tasks:
Since AK is now global, does it still snapshot the items as they are obtained? (See #10) If so, this will need a serious fix; otherwise the problem has gone away on its own - but that would really be too easy, wouldn't it? 
Update: Yes, it really needs a fix, although it's arguably not the highest priority still. I may just pass on it for the time being and see if I can get the Scanner to work with all tooltips, which will take care of this, too. Not part of this issue, anyway, so no checkbox to cross!

**Comment by emtfouru** [comment]
still having issues with 7.3 the new AP items will not show up on the addon.

**Comment by rdw-software** [comment]
If you have tried the newest alpha and it's still not showing up, please let me know the specific item and I will look into it. I literally haven't played since the patch hit and I've yet to test everything properly, which I am hoping to get done next week - sorry for the wait :)

PS: This is a different issue, since it's about the changes to the Artifact Knowledge system. The new items should've been added in 4722ddb08cc0c467fc38e2df3eb8d68e38ff0f35 (AKA r26-alpha on Curse).

**Comment by rdw-software** [comment]
Fixed with da25cbdc1a272e7563117b52603d152f8146bbc1 (r26-beta)
